from fastapi import APIRouter, HTTPException
from fastapi.responses import FileResponse
from typing import Dict, Any
from ...services.project_manager import project_manager
from pathlib import Path
import zipfile
import json
import os
from datetime import datetime

router = APIRouter()

@router.get("/{project_id}/package")
async def package_project(project_id: str):
    project = project_manager.get_project(project_id)
    if not project:
        raise HTTPException(status_code=404, detail="Project not found")
    
    try:
        from ...core.workspace import workspace_manager
        project_path = workspace_manager.get_project_path(project_id)
        
        # Create zip
        zip_path = Path(f"/tmp/{project_id}.zip")
        
        with zipfile.ZipFile(zip_path, 'w', zipfile.ZIP_DEFLATED) as zipf:
            # Add all project files
            for file_path in project_path.rglob("*"):
                if file_path.is_file():
                    # Skip node_modules, .git, etc
                    if 'node_modules' in str(file_path) or '.git' in str(file_path) or '__pycache__' in str(file_path):
                        continue
                    arcname = file_path.relative_to(project_path)
                    zipf.write(file_path, arcname)
            
            # Add README
            features_str = ', '.join(project.features) if project.features else 'N/A'
            solution_str = json.dumps(project.solution, indent=2)
            tech_str = json.dumps(project.tech_stack, indent=2)
            verification_str = json.dumps(project.verification, indent=2)
            
            readme_content = f"# {project.name}\n\n"
            readme_content += f"## Problem Statement\n{project.problem_statement}\n\n"
            readme_content += f"## Abstract\n{project.abstract}\n\n"
            readme_content += f"## Architecture\n{solution_str}\n\n"
            readme_content += f"## Features\n{features_str}\n\n"
            readme_content += f"## Tech Stack\n{tech_str}\n\n"
            readme_content += "## Installation\n```\nnpm install\nnpm run dev\n```\n\n"
            readme_content += "Backend:\n```\ncd backend\npip install -r requirements.txt\nuvicorn main:app --reload --port 8001\n```\n\n"
            readme_content += f"## Project Info\n- Project ID: {project.project_id}\n- Stage: {project.stage.value}\n- Files: {len(project.file_changes)}\n\n"
            readme_content += f"## Verification\n{verification_str}\n\n"
            readme_content += "Generated by RLCD Agentic Engineering IDE\n"
            
            zipf.writestr("README.md", readme_content)
            
            # Add project state
            zipf.writestr("project_state.json", json.dumps(project.model_dump(mode='json'), indent=2, default=str))
        
        return FileResponse(
            path=str(zip_path),
            filename=f"{project.name.replace(' ', '_')}_{project_id[:8]}.zip",
            media_type="application/zip"
        )
    
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@router.get("/{project_id}/export/abstract")
async def export_abstract(project_id: str):
    project = project_manager.get_project(project_id)
    if not project:
        raise HTTPException(status_code=404, detail="Project not found")
    
    return {
        "success": True,
        "abstract": project.abstract,
        "project_name": project.name
    }

@router.get("/{project_id}/export/architecture")
async def export_architecture(project_id: str):
    project = project_manager.get_project(project_id)
    if not project:
        raise HTTPException(status_code=404, detail="Project not found")
    
    return {
        "success": True,
        "architecture": project.solution,
        "tech_stack": project.tech_stack
    }

@router.get("/{project_id}/export/trajectories")
async def export_trajectories(project_id: str):
    project = project_manager.get_project(project_id)
    if not project:
        raise HTTPException(status_code=404, detail="Project not found")
    
    from ...services.reward import reward_service
    trajs = reward_service.get_trajectories(project_id)
    
    return {
        "success": True,
        "trajectories": trajs,
        "count": len(trajs)
    }

@router.get("/{project_id}/readme")
async def generate_readme(project_id: str):
    project = project_manager.get_project(project_id)
    if not project:
        raise HTTPException(status_code=404, detail="Project not found")
    
    features_list = ""
    if project.features:
        for f in project.features:
            features_list += f"- {f}\n"
    else:
        features_list = "- Dashboard\n- Monitoring\n"
    
    arch_str = ""
    if isinstance(project.solution, dict):
        arch_str = json.dumps(project.solution.get('architecture', {}), indent=2)
    
    frontend_stack = "React, TypeScript, Tailwind"
    if project.tech_stack.get('frontend'):
        frontend_stack = ', '.join(project.tech_stack.get('frontend', []))
    
    backend_stack = "FastAPI, PostgreSQL"
    if project.tech_stack.get('backend'):
        backend_stack = ', '.join(project.tech_stack.get('backend', []))
    
    api_list = ""
    if isinstance(project.solution, dict) and project.solution.get('api_requirements'):
        for api_item in project.solution.get('api_requirements', []):
            api_list += f"- {api_item}\n"
    else:
        api_list = "- /api/sensors\n- /api/analytics\n"
    
    deployment = "Docker"
    if isinstance(project.solution, dict):
        deployment = project.solution.get('deployment_requirements', 'Docker + Nginx')
    
    readme = f"# {project.name}\n\n"
    readme += f"## Problem\n{project.problem_statement}\n\n"
    readme += f"## Solution\n{project.abstract}\n\n"
    readme += f"## Features\n{features_list}\n\n"
    readme += f"## Architecture\n{arch_str}\n\n"
    readme += f"## Technology Stack\n**Frontend:** {frontend_stack}\n**Backend:** {backend_stack}\n\n"
    readme += "## Installation\n\n### Frontend\n```bash\nnpm install\nnpm run dev\n```\n\n"
    readme += "### Backend\n```bash\ncd backend\npip install -r requirements.txt\nuvicorn main:app --host 0.0.0.0 --port 8001 --reload\n```\n\n"
    readme += f"## API Endpoints\n{api_list}\n\n"
    readme += "## Testing\n```bash\nnpm run build\nnpm test\n```\n\n"
    readme += f"## Deployment\n{deployment}\n\n"
    readme += f"## Project Status\n- Stage: {project.stage.value}\n- Files: {len(project.file_changes)}\n- Decisions: {len(project.decisions)}\n\n"
    readme += "## Generated By\nRLCD Agentic Engineering IDE\n\n"
    readme += f"Project ID: {project.project_id}\n"
    
    return {
        "success": True,
        "readme": readme
    }
